/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.api2.vue;

import com.app.api2.artcile.Connexion;
import com.app.api2.artcile.Produit;
import com.app.api2.artcile.User;
import com.app.api2.metier.ProduitMetier;
import com.app.api2.metier.UserMetier;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    Produit p = new Produit();
    User u = new User();
    ProduitMetier pm= new ProduitMetier();
    UserMetier um= new UserMetier();
    public Welcome() {
        um.getUserbyid(u.getId());
        if(u.isAdmin()==true){
        initComponents();
        }
        else{
             jPanel1.add(jTabbedPane5);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        utilisateurText = new javax.swing.JTextField();
        motdepasseText = new javax.swing.JTextField();
        nomText = new javax.swing.JTextField();
        userScroll = new javax.swing.JComboBox<>();
        ajouterutilisateurBoutton = new javax.swing.JButton();
        modifierutilisateurButton = new javax.swing.JButton();
        supprimerutilisateurButton = new javax.swing.JButton();
        annulerutilisateurButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prenomText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        utilisateurTab = new javax.swing.JTable();
        chercherButton = new javax.swing.JButton();
        chercherutilisateurText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        referenceText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        designationText = new javax.swing.JTextField();
        emplacementText = new javax.swing.JTextField();
        StatusScroll = new javax.swing.JComboBox<>();
        ajouterproduitButton = new javax.swing.JButton();
        modifierproduitButton = new javax.swing.JButton();
        supprimerproduitButton = new javax.swing.JButton();
        annulerproduitButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        chercherproduitButton = new javax.swing.JButton();
        chercherproduitText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produitTab = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        referencetravailText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        designationtravailText = new javax.swing.JTextField();
        emplacementtravailText = new javax.swing.JTextField();
        passageText = new javax.swing.JTextField();
        validertravailButton = new javax.swing.JButton();
        annulertravailButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Utilisateur");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mot de passe");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Prenom");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images.png")); // NOI18N
        jLabel6.setText("Gestion Utilisateur");

        utilisateurText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurTextActionPerformed(evt);
            }
        });

        userScroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Producteur", "Magasinier", "Nettoyeur", "Controleur", " " }));
        userScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userScrollActionPerformed(evt);
            }
        });

        ajouterutilisateurBoutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ajouterutilisateurBoutton.setText("Ajouter");
        ajouterutilisateurBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterutilisateurBouttonActionPerformed(evt);
            }
        });

        modifierutilisateurButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modifierutilisateurButton.setText("Modifier");
        modifierutilisateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierutilisateurButtonActionPerformed(evt);
            }
        });

        supprimerutilisateurButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supprimerutilisateurButton.setText("Supprimer");
        supprimerutilisateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerutilisateurButtonActionPerformed(evt);
            }
        });

        annulerutilisateurButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        annulerutilisateurButton.setText("Annuler");
        annulerutilisateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerutilisateurButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(utilisateurText)
                    .addComponent(motdepasseText)
                    .addComponent(nomText)
                    .addComponent(userScroll, 0, 113, Short.MAX_VALUE)
                    .addComponent(prenomText)
                    .addComponent(emailText))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimerutilisateurButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifierutilisateurButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouterutilisateurBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annulerutilisateurButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(utilisateurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterutilisateurBoutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(motdepasseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierutilisateurButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimerutilisateurButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerutilisateurButton)
                    .addComponent(prenomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Utilisateur", jPanel1);

        utilisateurTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Utilisateur", "Mot de passe", "Nom", "Prenom", "Email", "Producteur", "Magasinier", "Nettoyeur", "Controleur", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        utilisateurTab.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                utilisateurTabComponentAdded(evt);
            }
        });
        utilisateurTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                utilisateurTabMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(utilisateurTab);

        chercherButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chercherButton.setText("Chercher");
        chercherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images.png")); // NOI18N
        jLabel1.setText("Liste Utilisateurs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chercherutilisateurText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chercherButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(chercherutilisateurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chercherButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane5.addTab("Liste_utilisateur", jPanel2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images.png")); // NOI18N
        jLabel9.setText("Gestion Produit");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Reference");

        referenceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceTextActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Designation");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Emplacement");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Status");

        StatusScroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Production", "Stockage", "Nettoyage", "Controle", "Blocage" }));
        StatusScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusScrollActionPerformed(evt);
            }
        });

        ajouterproduitButton.setText("Ajouter");
        ajouterproduitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterproduitButtonActionPerformed(evt);
            }
        });

        modifierproduitButton.setText("Modifier");
        modifierproduitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierproduitButtonActionPerformed(evt);
            }
        });

        supprimerproduitButton.setText("Supprimer");
        supprimerproduitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerproduitButtonActionPerformed(evt);
            }
        });

        annulerproduitButton.setText("Annuler");
        annulerproduitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerproduitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emplacementText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(designationText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(referenceText, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimerproduitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouterproduitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifierproduitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annulerproduitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(referenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterproduitButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(modifierproduitButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emplacementText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(supprimerproduitButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(StatusScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerproduitButton))
                .addGap(0, 160, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Produit", jPanel3);

        chercherproduitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chercherproduitButton.setText("Chercher");
        chercherproduitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherproduitButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images.png")); // NOI18N
        jLabel14.setText("Liste Produits");

        produitTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reference", "Designation", "Emplacement", "Production", "Stockage", "Nettoyage", "Controle", "Blocage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        produitTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                produitTabMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(produitTab);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chercherproduitText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chercherproduitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chercherproduitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercherproduitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Liste_produit", jPanel4);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images.png")); // NOI18N
        jLabel15.setText("Zone Travail");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Reference");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Designation");

        referencetravailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referencetravailTextActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Emplacement");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Nombre passage");

        designationtravailText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        passageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passageTextActionPerformed(evt);
            }
        });

        validertravailButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        validertravailButton.setText("Valider");
        validertravailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validertravailButtonActionPerformed(evt);
            }
        });

        annulertravailButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        annulertravailButton.setText("Annuler");
        annulertravailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulertravailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emplacementtravailText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(designationtravailText, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(referencetravailText)))
                            .addComponent(passageText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(validertravailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(annulertravailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(202, 202, 202))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(referencetravailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(designationtravailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(emplacementtravailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(passageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validertravailButton)
                    .addComponent(annulertravailButton))
                .addGap(0, 71, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Zone_travail", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 573, 409);
    }// </editor-fold>//GEN-END:initComponents

    private void utilisateurTabComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_utilisateurTabComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_utilisateurTabComponentAdded

    private void ajouterutilisateurBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterutilisateurBouttonActionPerformed
    
    u.setId(utilisateurText.getText());
    u.setMdp(motdepasseText.getText());
    u.setNom(nomText.getText());
    u.setPrenom(prenomText.getText());
    u.setEmail(emailText.getText());
    userScrollActionPerformed(evt);      
    um.ajouterUser(u);
    }//GEN-LAST:event_ajouterutilisateurBouttonActionPerformed

    private void passageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passageTextActionPerformed

    private void modifierutilisateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierutilisateurButtonActionPerformed
    u.setId(utilisateurText.getText());
    um.getUserbyid(u.getId());
    u.setMdp(motdepasseText.getText());
    u.setNom(nomText.getText());
    u.setPrenom(prenomText.getText());
    u.setEmail(emailText.getText());
    userScrollActionPerformed(evt); 
    um.modifierUser(u);
    }//GEN-LAST:event_modifierutilisateurButtonActionPerformed

    private void supprimerutilisateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerutilisateurButtonActionPerformed
        u.setId(utilisateurText.getText());
        um.getUserbyid(u.getId());
        um.supprimerUser(u.getId());
    }//GEN-LAST:event_supprimerutilisateurButtonActionPerformed

    private void annulerutilisateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerutilisateurButtonActionPerformed
      utilisateurText.setText("");
      motdepasseText.setText("");
      nomText.setText("");
      prenomText.setText("");
      emailText.setText("");
    }//GEN-LAST:event_annulerutilisateurButtonActionPerformed

    private void userScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userScrollActionPerformed
    
    if(userScroll.getSelectedItem().equals("Admin")){
        u.setAdmin(true);
    }
    else if(userScroll.getSelectedItem().equals("Producteur")){
        u.setProducteur(true);
    }
    else if(userScroll.getSelectedItem().equals("Nettoyeur")){
        u.setNettoyeur(true);
    }
    else if(userScroll.getSelectedItem().equals("Controleur")){
        u.setControleur(true);
    }
    else{
        u.setMagasinier(true);
    }
    
    }//GEN-LAST:event_userScrollActionPerformed

    private void utilisateurTabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilisateurTabMouseReleased
        
        int select =utilisateurTab.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)utilisateurTab.getModel();
        u.setId(model.getValueAt(select, 0).toString());
        u.setMdp(model.getValueAt(select, 1).toString());
        u.setNom(model.getValueAt(select, 2).toString());
        u.setPrenom(model.getValueAt(select, 3).toString());
        u.setEmail(model.getValueAt(select, 4).toString());
        u.setProducteur((boolean)model.getValueAt(select, 5));
        u.setMagasinier((boolean)model.getValueAt(select, 6));
        u.setNettoyeur((boolean)model.getValueAt(select, 7));
        u.setControleur((boolean)model.getValueAt(select, 8));
        u.setAdmin((boolean)model.getValueAt(select, 9));
        um.getUser();
        
    }//GEN-LAST:event_utilisateurTabMouseReleased

    private void chercherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherButtonActionPerformed
       u.setId(chercherutilisateurText.getText());
       um.getUserbyid(u.getId());
    }//GEN-LAST:event_chercherButtonActionPerformed

    private void ajouterproduitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterproduitButtonActionPerformed
   p.setRef(referenceText.getX());
   p.setDesignation(designationText.getText());
   p.setEmplacement(emplacementText.getText());
   StatusScrollActionPerformed(evt);
   pm.ajouterProduit(p);
   um.getUser();
  
    }//GEN-LAST:event_ajouterproduitButtonActionPerformed

    private void StatusScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusScrollActionPerformed
        if(StatusScroll.getSelectedItem().equals("Production")){
            p.setProduction(1);
        }
        else if(StatusScroll.getSelectedItem().equals("Nettoyage")){
            p.setStockage(true);
        }
       else if(StatusScroll.getSelectedItem().equals("Controle")){
            p.setControle(true);
        }
       else if(StatusScroll.getSelectedItem().equals("Stockage")){
            p.setStockage(true);
        }
       else{
           p.setBlocage(true);
       }
        
    }//GEN-LAST:event_StatusScrollActionPerformed

    private void modifierproduitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierproduitButtonActionPerformed
       String reftxt = referenceText.getText();
       int ref= Integer.parseInt(reftxt);
        p.setRef(ref);
        pm.chercherProduit(p.getProduction());
        p.setDesignation(designationText.getText());
        p.setEmplacement(emplacementText.getText());
        StatusScrollActionPerformed(evt);
        pm.modifierProduit(p);    
    }//GEN-LAST:event_modifierproduitButtonActionPerformed

    private void supprimerproduitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerproduitButtonActionPerformed
    String reftxt = referenceText.getText();
       int ref= Integer.parseInt(reftxt);
        p.setRef(ref);
        pm.chercherProduit(ref);
        pm.supprimerProduit(ref);
    }//GEN-LAST:event_supprimerproduitButtonActionPerformed

    private void annulerproduitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerproduitButtonActionPerformed
       referenceText.setText("");
       designationText.setText("");
       emplacementText.setText("");
    }//GEN-LAST:event_annulerproduitButtonActionPerformed

    private void chercherproduitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherproduitButtonActionPerformed
   String reftxt = chercherproduitText.getText();
       int ref= Integer.parseInt(reftxt);
        p.setRef(ref);
        pm.chercherProduit(ref);
    }//GEN-LAST:event_chercherproduitButtonActionPerformed

    private void produitTabMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produitTabMouseReleased
       int select = produitTab.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel)produitTab.getModel();
       p.setRef((int) model.getValueAt(select, 0));
       p.setDesignation((String)model.getValueAt(select, 1));
       p.setEmplacement((String)model.getValueAt(select, 2));
       p.setProduction((int) model.getValueAt(select, 3));
       p.setNettoyage((boolean)model.getValueAt(select, 4));
       p.setControle((boolean)model.getValueAt(select, 5));
       p.setStockage((boolean)model.getValueAt(select, 6));
       p.setBlocage((boolean)model.getValueAt(select, 7));
       pm.getProduit();
    }//GEN-LAST:event_produitTabMouseReleased

    private void utilisateurTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurTextActionPerformed
        u.setId(utilisateurText.getText());
        um.getUserbyid(u.getId());
        motdepasseText.setText(u.getMdp());
        nomText.setText(u.getNom());
        prenomText.setText(u.getPrenom());
        emailText.setText(u.getEmail());
        
    }//GEN-LAST:event_utilisateurTextActionPerformed

    private void referenceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceTextActionPerformed
       String reftxt = referenceText.getText();
       int ref= Integer.parseInt(reftxt);
       p.setRef(ref);
       pm.chercherProduit(ref);
       designationText.setText(p.getDesignation());
       emplacementText.setText(p.getEmplacement());
       if(p.getProduction()!=0){
           StatusScroll.setSelectedItem("Production");
       }
       else if(p.isNettoyage()==true){
           StatusScroll.setSelectedItem("Nettoyage");
       }
        else if(p.isControle()==true){
           StatusScroll.setSelectedItem("Controle");
       }
        else if(p.isStockage()==true){
           StatusScroll.setSelectedItem("Stockage");
       }
        else{
           StatusScroll.setSelectedItem("Blocage"); 
        }
       
      
    }//GEN-LAST:event_referenceTextActionPerformed

    private void validertravailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validertravailButtonActionPerformed
     
         pm.validProduitstat(p);
         
    }//GEN-LAST:event_validertravailButtonActionPerformed

    private void referencetravailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referencetravailTextActionPerformed
        String reftxt = referencetravailText.getText();
        int ref= Integer.parseInt(reftxt);
        p.setRef(ref);
         pm.chercherProduit(ref);
         pm.comptage();
         designationtravailText.setText(p.getDesignation());
         emplacementtravailText.setText(p.getEmplacement());
         String passage = Integer. toString(p.getProduction());
         passageText.setText(passage);
    }//GEN-LAST:event_referencetravailTextActionPerformed

    private void annulertravailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulertravailButtonActionPerformed
       pm.annulProduitstat(p);
    }//GEN-LAST:event_annulertravailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StatusScroll;
    private javax.swing.JButton ajouterproduitButton;
    private javax.swing.JButton ajouterutilisateurBoutton;
    private javax.swing.JButton annulerproduitButton;
    private javax.swing.JButton annulertravailButton;
    private javax.swing.JButton annulerutilisateurButton;
    private javax.swing.JButton chercherButton;
    private javax.swing.JButton chercherproduitButton;
    private javax.swing.JTextField chercherproduitText;
    private javax.swing.JTextField chercherutilisateurText;
    private javax.swing.JTextField designationText;
    private javax.swing.JTextField designationtravailText;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField emplacementText;
    private javax.swing.JTextField emplacementtravailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JButton modifierproduitButton;
    private javax.swing.JButton modifierutilisateurButton;
    private javax.swing.JTextField motdepasseText;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField passageText;
    private javax.swing.JTextField prenomText;
    private javax.swing.JTable produitTab;
    private javax.swing.JTextField referenceText;
    private javax.swing.JTextField referencetravailText;
    private javax.swing.JButton supprimerproduitButton;
    private javax.swing.JButton supprimerutilisateurButton;
    private javax.swing.JComboBox<String> userScroll;
    private javax.swing.JTable utilisateurTab;
    private javax.swing.JTextField utilisateurText;
    private javax.swing.JButton validertravailButton;
    // End of variables declaration//GEN-END:variables
}
